### ISSUE TITLE
MiniPC Moovah Configuration.

### ISSUE THREAD

**Issue by shrikantgond** [WinjitTech/moovah#4]
Prepare MiniPC with all the configurations for moovah project.
Please provide the steps as a comment to this.

**Comment by Rohit-Salunke** [comment]
Moovah Project with MiniPC is ready steps to configure MiniPC with Ubuntu 15.04 is attached here.
[MoovahMiniPc setup.txt](https://github.com/WinjitTech/moovah/files/9069/MoovahMiniPc.setup.txt)
